import { useGetDashboard } from '@workspace/api-client-react';
import { ArrowUpRight, BarChart3, CalendarCheck2, TrendingDown, UsersRound } from 'lucide-react';
import { Link } from 'wouter';
import { AppShell, EmptyState, ErrorState, LoadingPanel, PageHeading, StatCard } from '@/components/edupulse';

function Meter({ label, value, tone = 'green' }: { label: string; value: number; tone?: string }) {
  return <div className="space-y-2"><div className="flex items-center justify-between text-sm"><span className="font-semibold">{label}</span><span className="font-mono text-xs text-muted-foreground">{value.toFixed(1)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${tone === 'gold' ? 'bg-accent' : 'bg-primary'}`} style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div></div>;
}

export default function Dashboard() {
  const dashboard = useGetDashboard();
  if (dashboard.isLoading) return <AppShell><LoadingPanel /></AppShell>;
  if (dashboard.isError || !dashboard.data) return <AppShell><ErrorState retry={() => dashboard.refetch()} /></AppShell>;
  const data = dashboard.data;
  return <AppShell><div className="page-enter"><PageHeading eyebrow="Monday · faculty brief" title="Good morning, Ananya." description="A quick read on your cohort before the day gets moving." action={<Link href="/attendance" data-testid="link-take-attendance" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground shadow-sm transition-all hover:brightness-110 active:scale-[.98]">Take attendance <ArrowUpRight size={16} /></Link>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Students" value={String(data.totalStudents)} detail="in your current cohort" icon={UsersRound} /><StatCard label="Attendance" value={`${data.overallAttendance.toFixed(1)}%`} detail="across all subjects" icon={CalendarCheck2} accent={data.overallAttendance < 75 ? 'red' : 'green'} /><StatCard label="Average marks" value={`${data.averageMarks.toFixed(1)}%`} detail="internal + practical" icon={BarChart3} accent="gold" /><StatCard label="Needs a check-in" value={String(data.lowAttendance.length)} detail="attendance below 75%" icon={TrendingDown} accent="red" /></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <section className="rounded-xl border border-border bg-card p-6 shadow-xs"><div className="mb-7 flex items-start justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">Subject pulse</div><h2 className="mt-2 font-serif text-xl font-semibold">Where the room stands</h2></div><BarChart3 size={20} className="text-muted-foreground" /></div><div className="space-y-6">{data.subjectAttendance.map((item) => <div key={item.subject}><Meter label={item.subject} value={item.value} /></div>)}</div><div className="mt-8 border-t border-border pt-5"><div className="mb-4 font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">Average marks / 50</div><div className="grid grid-cols-2 gap-x-6 gap-y-4">{data.subjectPerformance.map((item) => <Meter key={item.subject} label={item.subject} value={item.value * 2} tone="gold" />)}</div></div></section>
      <section className="rounded-xl border border-border bg-card p-6 shadow-xs"><div className="flex items-start justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-destructive">Early attention</div><h2 className="mt-2 font-serif text-xl font-semibold">Low attendance</h2></div><Link href="/attendance" data-testid="link-review-attendance" className="text-xs font-semibold text-primary hover:underline">Review all</Link></div>{data.lowAttendance.length ? <div className="mt-5 divide-y divide-border">{data.lowAttendance.map((student) => <div key={`${student.subject}-${student.value}`} data-testid={`row-low-attendance-${student.subject}`} className="flex items-center justify-between py-4 first:pt-0"><div><div className="text-sm font-semibold">{student.subject}</div><div className="mt-1 text-xs text-muted-foreground">Needs a gentle follow-up</div></div><div className="font-mono text-sm text-destructive">{student.value.toFixed(1)}%</div></div>)}</div> : <div className="mt-6"><EmptyState title="A clear board" description="No subject is currently below the 75% attendance threshold." /></div>}</section>
    </div>
    <section className="mt-5 rounded-xl border border-border bg-card p-6 shadow-xs"><div className="mb-5 flex items-center justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">Recently enrolled</div><h2 className="mt-2 font-serif text-xl font-semibold">New faces in the cohort</h2></div><Link href="/students" data-testid="link-view-students" className="text-xs font-semibold text-primary hover:underline">View students</Link></div>{data.recentStudents.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{data.recentStudents.map((student) => <Link href="/students" key={student.id} data-testid={`card-recent-student-${student.id}`} className="group rounded-lg border border-border bg-background p-4 transition-colors hover:border-primary/50"><div className="flex items-center justify-between"><div className="grid h-9 w-9 place-items-center rounded-full bg-secondary font-serif font-semibold text-secondary-foreground">{student.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</div><ArrowUpRight size={15} className="text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></div><div className="mt-4 truncate text-sm font-semibold">{student.name}</div><div className="mt-1 font-mono text-[10px] text-muted-foreground">{student.enrollmentNo}</div></Link>)}</div> : <EmptyState title="No recent students" description="Newly added students will appear here." />}</section>
  </div></AppShell>;
}