import { useMemo, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { getGetStudentQueryKey, getListStudentsQueryKey, useCreateStudent, useDeleteStudent, useGetStudent, useListStudents, useUpdateStudent, type Student, type StudentInput } from '@workspace/api-client-react';
import { Mail, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { AppShell, Button, EmptyState, ErrorState, Field, Input, LoadingPanel, Modal, PageHeading, Toast } from '@/components/edupulse';

const blank: StudentInput = { name: '', enrollmentNo: '', email: '', semester: 4, branch: 'Computer Science & Engineering' };

function StudentForm({ initial, onClose, onSaved }: { initial?: Student; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState<StudentInput>(initial ? { name: initial.name, enrollmentNo: initial.enrollmentNo, email: initial.email, semester: initial.semester, branch: initial.branch } : blank);
  const [error, setError] = useState('');
  const client = useQueryClient();
  const create = useCreateStudent();
  const update = useUpdateStudent();
  const pending = create.isPending || update.isPending;
  const change = (key: keyof StudentInput, value: string) => setForm((current) => ({ ...current, [key]: key === 'semester' ? Number(value) : value }));
  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    if (!form.name.trim() || !form.enrollmentNo.trim() || !form.email.trim() || !form.branch.trim()) { setError('Complete every field before saving.'); return; }
    const onSuccess = () => { client.invalidateQueries({ queryKey: getListStudentsQueryKey() }); onSaved(); onClose(); };
    const onError = () => setError('The student could not be saved. Please try again.');
    if (initial) update.mutate({ id: initial.id, data: form }, { onSuccess, onError }); else create.mutate({ data: form }, { onSuccess, onError });
  };
  return <form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Full name"><Input data-testid="input-student-name" value={form.name} onChange={(e) => change('name', e.target.value)} placeholder="Student name" /></Field><Field label="Enrollment number"><Input data-testid="input-student-enrollment" value={form.enrollmentNo} onChange={(e) => change('enrollmentNo', e.target.value)} placeholder="CSE24-001" /></Field><Field label="College email"><Input data-testid="input-student-email" type="email" value={form.email} onChange={(e) => change('email', e.target.value)} placeholder="student@college.edu" /></Field><Field label="Semester"><Input data-testid="input-student-semester" type="number" min="1" value={form.semester} onChange={(e) => change('semester', e.target.value)} /></Field></div><Field label="Branch"><Input data-testid="input-student-branch" value={form.branch} onChange={(e) => change('branch', e.target.value)} placeholder="Computer Science & Engineering" /></Field>{error && <div data-testid="status-student-form" className="rounded-lg bg-destructive/10 px-3 py-2 text-xs text-destructive">{error}</div>}<div className="flex justify-end gap-2 border-t border-border pt-5"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button data-testid="button-save-student" disabled={pending} type="submit">{pending ? 'Saving…' : initial ? 'Save changes' : 'Add student'}</Button></div></form>;
}

export default function Students() {
  const students = useListStudents();
  const client = useQueryClient();
  const remove = useDeleteStudent();
  const [search, setSearch] = useState('');
  const [modal, setModal] = useState<'create' | 'edit' | 'detail' | null>(null);
  const [selected, setSelected] = useState<number | null>(null);
  const [notice, setNotice] = useState('');
  const list = students.data ?? [];
  const filtered = useMemo(() => list.filter((student) => `${student.name} ${student.enrollmentNo} ${student.email} ${student.branch}`.toLowerCase().includes(search.toLowerCase())), [list, search]);
  const detail = useGetStudent(selected ?? 0, { query: { enabled: modal === 'detail' && selected !== null, queryKey: getGetStudentQueryKey(selected ?? 0) } });
  const openEdit = (student: Student) => { setSelected(student.id); setModal('edit'); };
  const deleteOne = (student: Student) => { if (!window.confirm(`Remove ${student.name} from this cohort?`)) return; remove.mutate({ id: student.id }, { onSuccess: () => { client.invalidateQueries({ queryKey: getListStudentsQueryKey() }); setNotice('Student removed'); setTimeout(() => setNotice(''), 2600); }, onError: () => { setNotice('Could not remove student'); setTimeout(() => setNotice(''), 2600); } }); };
  return <AppShell><div className="page-enter"><PageHeading eyebrow="Cohort directory" title="Students" description="Keep the people behind the numbers easy to find and easy to support." action={<Button data-testid="button-add-student" onClick={() => { setSelected(null); setModal('create'); }}><Plus size={17} />Add student</Button>} />
    <div className="mb-5 flex flex-col gap-3 rounded-xl border border-border bg-card p-3 shadow-xs sm:flex-row sm:items-center sm:justify-between"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={16} /><input data-testid="input-student-search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name, enrollment or branch" className="focus-ring h-10 w-full rounded-lg bg-background pl-9 pr-3 text-sm outline-none sm:w-[320px]" /></div><div className="flex items-center gap-3 px-2 text-xs text-muted-foreground"><span className="font-mono text-foreground">{filtered.length}</span> of {list.length} students</div></div>
    {students.isLoading ? <LoadingPanel /> : students.isError ? <ErrorState retry={() => students.refetch()} /> : !filtered.length ? <EmptyState title={search ? 'No students match that search' : 'Your directory is empty'} description={search ? 'Try a name, enrollment number or branch.' : 'Add your first student to begin tracking progress.'} action={!search && <Button onClick={() => setModal('create')}><Plus size={16} />Add first student</Button>} /> : <div className="overflow-hidden rounded-xl border border-border bg-card shadow-xs"><div className="hidden grid-cols-[1.5fr_1fr_1.3fr_.7fr_1fr] gap-4 border-b border-border bg-muted/50 px-5 py-3 font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground md:grid"><div>Student</div><div>Enrollment</div><div>Contact</div><div>Term</div><div className="text-right">Actions</div></div><div className="divide-y divide-border">{filtered.map((student) => <div key={student.id} data-testid={`row-student-${student.id}`} className="group grid gap-3 px-5 py-4 transition-colors hover:bg-muted/35 md:grid-cols-[1.5fr_1fr_1.3fr_.7fr_1fr] md:items-center md:gap-4"><button data-testid={`button-view-student-${student.id}`} onClick={() => { setSelected(student.id); setModal('detail'); }} className="flex min-w-0 items-center gap-3 text-left"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-secondary font-serif font-semibold text-secondary-foreground">{student.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</div><div className="min-w-0"><div className="truncate text-sm font-semibold">{student.name}</div><div className="truncate text-xs text-muted-foreground md:hidden">{student.enrollmentNo} · {student.branch}</div></div></button><div className="hidden font-mono text-xs text-muted-foreground md:block">{student.enrollmentNo}</div><div className="hidden truncate text-xs text-muted-foreground md:block">{student.email}</div><div className="hidden text-sm md:block">Sem {student.semester}</div><div className="flex justify-end gap-1"><button data-testid={`button-edit-student-${student.id}`} onClick={() => openEdit(student)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-foreground"><Pencil size={15} /></button><button data-testid={`button-delete-student-${student.id}`} onClick={() => deleteOne(student)} className="rounded-lg p-2 text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 size={15} /></button></div></div>)}</div></div>}
    {modal === 'create' && <Modal title="Add a student" description="Create a profile for a new member of your cohort." onClose={() => setModal(null)}><StudentForm onClose={() => setModal(null)} onSaved={() => { setNotice('Student added to the cohort'); setTimeout(() => setNotice(''), 2600); }} /></Modal>}
    {modal === 'edit' && selected !== null && <Modal title="Edit student" description="Keep this student’s record current." onClose={() => setModal(null)}>{list.find((student) => student.id === selected) && <StudentForm initial={list.find((student) => student.id === selected)} onClose={() => setModal(null)} onSaved={() => { setNotice('Student details updated'); setTimeout(() => setNotice(''), 2600); }} />}</Modal>}
    {modal === 'detail' && selected !== null && <Modal title={detail.data?.name ?? 'Student detail'} description="A focused view of this student’s profile." onClose={() => setModal(null)}>{detail.isLoading ? <div className="space-y-3"><div className="skeleton h-16" /><div className="skeleton h-11" /><div className="skeleton h-11" /></div> : detail.isError || !detail.data ? <ErrorState retry={() => detail.refetch()} /> : <div className="space-y-5"><div className="flex items-center gap-4 rounded-xl bg-muted/60 p-4"><div className="grid h-14 w-14 place-items-center rounded-full bg-primary font-serif text-xl font-semibold text-primary-foreground">{detail.data.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</div><div><div className="font-serif text-xl font-semibold">{detail.data.name}</div><div className="font-mono text-xs text-muted-foreground">{detail.data.enrollmentNo}</div></div></div><div className="grid gap-4 sm:grid-cols-2"><div><div className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground">Email</div><div className="mt-1 flex items-center gap-2 text-sm"><Mail size={14} className="text-primary" />{detail.data.email}</div></div><div><div className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground">Academic term</div><div className="mt-1 text-sm font-semibold">Semester {detail.data.semester}</div></div><div className="sm:col-span-2"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground">Branch</div><div className="mt-1 text-sm font-semibold">{detail.data.branch}</div></div></div><div className="flex justify-end border-t border-border pt-5"><Button variant="secondary" onClick={() => setModal('edit')}>Edit profile</Button></div></div>}</Modal>}
    {notice && <Toast message={notice} />}
  </div></AppShell>;
}